#pragma once
// Generated from OpenFlights airlines.dat (active carriers) plus hand-added operators. ICAO 3-letter code -> short name.
#include <stdint.h>

struct AirlineEntry { const char* icao; const char* name; };

static const AirlineEntry AIRLINES[] = {
    {"AAA", "Ansett Australia"},
    {"AAF", "Aigle Azur"},
    {"AAH", "Aloha Airlines"},
    {"AAL", "American"},
    {"AAN", "Amsterdam"},
    {"AAQ", "Copterline"},
    {"AAR", "Asiana"},
    {"AAS", "Askari Aviation"},
    {"AAW", "Afriqiyah"},
    {"AAY", "Allegiant Air"},
    {"ABD", "Air Atlanta Icelan"},
    {"ABI", "Aviabus"},
    {"ABL", "Air Busan"},
    {"ABQ", "Airblue"},
    {"ABS", "Transwest Air"},
    {"ABX", "ABX Air"},
    {"ABY", "Air Arabia"},
    {"ACA", "Air Canada"},
    {"ACI", "Air Caledonie Inte"},
    {"ACP", "Astral Aviation"},
    {"ADE", "Ada Air"},
    {"ADH", "Air One"},
    {"ADO", "Hokkaido Internati"},
    {"ADR", "Adria Airways"},
    {"AEA", "Air Europa"},
    {"AEB", "Aero Benin"},
    {"AEE", "Aegean"},
    {"AEL", "Air Europe"},
    {"AER", "Alaska Central Exp"},
    {"AES", "ACES Colombia"},
    {"AEU", "Astraeus"},
    {"AEW", "Aerosvit"},
    {"AEY", "Air Italy"},
    {"AFG", "Ariana Afghan"},
    {"AFL", "Aeroflot"},
    {"AFR", "Air France"},
    {"AGV", "Air Glaciers"},
    {"AGX", "Aviogenex"},
    {"AHO", "Air Hamburg (AHO)"},
    {"AHY", "Azerbaijan"},
    {"AIA", "Avies"},
    {"AIC", "Air India"},
    {"AIO", "United States Air"},
    {"AIQ", "Thai AirAsia"},
    {"AIR", "Airlift Internatio"},
    {"AIZ", "Arkia Israel"},
    {"AJM", "Air Jamaica"},
    {"AJX", "Air Japan"},
    {"AKA", "Air Korea Co."},
    {"AKL", "Air Kiribati"},
    {"ALK", "SriLankan"},
    {"ALO", "Allegheny Commuter"},
    {"AMC", "Air Malta"},
    {"AML", "Air Malawi"},
    {"AMT", "ATA Airlines"},
    {"AMU", "Air Macau"},
    {"AMV", "AMC Airlines"},
    {"AMX", "Aeromexico"},
    {"ANA", "ANA"},
    {"ANE", "Air Nostrum"},
    {"ANG", "Air Niugini"},
    {"ANK", "Air Nippon"},
    {"ANO", "Airnorth"},
    {"ANT", "Air North Charter"},
    {"ANU", "Andalus Lineas Aer"},
    {"ANZ", "Air New Zealand"},
    {"APW", "Arrow Air"},
    {"ARD", "Aerocondor"},
    {"ARE", "Aires"},
    {"ARF", "Aero Flight"},
    {"ARG", "Aerolineas Arg"},
    {"ARU", "Aruba Airlines"},
    {"ASA", "Alaska"},
    {"ASD", "Air Sinai"},
    {"ASH", "Mesa Airlines"},
    {"ASL", "Air Serbia"},
    {"ASQ", "Atlantic Southeast"},
    {"ASZ", "Astrakhan"},
    {"ATC", "Air Tanzania"},
    {"ATM", "Airlines Of Tasman"},
    {"ATN", "Air Transport Intl"},
    {"AUA", "Austrian"},
    {"AUB", "Augsburg Airways"},
    {"AUH", "Abu Dhabi Amiri Fl"},
    {"AUI", "Ukraine Internatio"},
    {"AUL", "Aeroflot-Nord"},
    {"AUR", "Aurigny Air Servic"},
    {"AUT", "Austral Lineas Aer"},
    {"AVA", "Avianca - Aerovias"},
    {"AVN", "Air Vanuatu"},
    {"AWA", "Asia Wings"},
    {"AWC", "Titan"},
    {"AWE", "America West"},
    {"AWI", "Air Wisconsin"},
    {"AWM", "Asian Wings"},
    {"AWQ", "Indonesia AirAsia"},
    {"AWU", "Aeroline GmbH"},
    {"AWW", "Air Wales"},
    {"AXB", "Air India Express"},
    {"AXC", "Indochina"},
    {"AXE", "Air Explore"},
    {"AXL", "Air Exel"},
    {"AXM", "AirAsia"},
    {"AXZ", "Aereonautica milit"},
    {"AYZ", "Atlant-Soyuz"},
    {"AZA", "ITA Airways"},
    {"AZN", "Amaszonas"},
    {"AZU", "Azul"},
    {"AZW", "Air Zimbabwe"},
    {"BAG", "dba"},
    {"BAW", "British Airways"},
    {"BBC", "Biman Bangladesh"},
    {"BBG", "Bluebird Airways ("},
    {"BBO", "Flybaboo"},
    {"BBR", "Santa Barbara"},
    {"BCC", "BusinessAir"},
    {"BCN", "Ocean Air"},
    {"BCS", "European Air Trans"},
    {"BCY", "CityJet"},
    {"BEE", "Flybe"},
    {"BEL", "Brussels"},
    {"BER", "Air Berlin"},
    {"BEU", "Bateleur Air"},
    {"BGD", "Air Bangladesh"},
    {"BGY", "Bingo Airways"},
    {"BHP", "Belair Airlines"},
    {"BHS", "Bahamasair"},
    {"BIE", "Air Mediterranee"},
    {"BIH", "British Internatio"},
    {"BKF", "BF-Lento OY"},
    {"BKP", "Bangkok Airways"},
    {"BLF", "Blue1"},
    {"BLL", "Baltic Airlines"},
    {"BLS", "Bearskin Lake Air"},
    {"BLV", "Bellview"},
    {"BLX", "TUI fly Nordic"},
    {"BMA", "bmi"},
    {"BMI", "bmibaby"},
    {"BMJ", "Bemidji Airlines"},
    {"BMM", "Atlas Blue"},
    {"BMR", "British Midland Re"},
    {"BON", "Air Bosna"},
    {"BOT", "Air Botswana"},
    {"BOV", "Boliviana de Aviac"},
    {"BOX", "AeroLogic"},
    {"BPA", "Blue Panorama"},
    {"BPS", "Budapest Aircraft"},
    {"BQB", "Buquebus Lineas Ae"},
    {"BRA", "Braathens"},
    {"BRG", "Bering Air"},
    {"BRQ", "El-Buraq Air Trans"},
    {"BRS", "Brazilian Air Forc"},
    {"BRU", "Belavia Belarusian"},
    {"BSA", "Black Stallion"},
    {"BSX", "Bassaka airlines"},
    {"BTA", "ExpressJet"},
    {"BTI", "airBaltic"},
    {"BTM", "Air Batumi"},
    {"BTQ", "Boutique Air (Priv"},
    {"BTV", "Metro Batavia"},
    {"BUB", "Air Bourbon"},
    {"BUR", "Air Bucharest"},
    {"BUU", "Baikotovitchestria"},
    {"BVT", "Berjaya Air"},
    {"BWA", "Caribbean"},
    {"BWG", "Blue Wings"},
    {"BZE", "BRAZIL AIR"},
    {"BZH", "Brit Air"},
    {"CAI", "Corendon"},
    {"CAL", "China Airlines"},
    {"CAN", "Crest Aviation"},
    {"CAP", "CanXplorer"},
    {"CAW", "Comair"},
    {"CAY", "Cayman Airways"},
    {"CBG", "GX Airlines"},
    {"CCA", "Air China"},
    {"CCB", "CARICOM AIRWAYS (B"},
    {"CCC", "CCML Airlines"},
    {"CCG", "Central Connect"},
    {"CCM", "Corse-Mediterranee"},
    {"CDG", "Shandong"},
    {"CDN", "Canadian"},
    {"CDP", "Aero Condor Peru"},
    {"CEB", "Cebu Pacific"},
    {"CEL", "CEIBA Intercontine"},
    {"CEO", "Comfort Express Vi"},
    {"CES", "China Eastern"},
    {"CEY", "Air Century"},
    {"CFE", "BA CityFlyer"},
    {"CFG", "Condor"},
    {"CGK", "Click Airways"},
    {"CGP", "Cargo Plus"},
    {"CHB", "West Air China"},
    {"CHH", "Hainan Airlines"},
    {"CHP", "Consorcio Aviaxsa"},
    {"CHQ", "Chautauqua"},
    {"CHW", "Charter Air"},
    {"CIF", "CB Airways UK ( In"},
    {"CIM", "Cimber Air"},
    {"CIX", "City Connexion"},
    {"CJC", "Colgan Air"},
    {"CKS", "Kalitta"},
    {"CLH", "Lufthansa CityLine"},
    {"CLI", "Calima Aviacion"},
    {"CLJ", "Cello Aviation"},
    {"CLW", "Centralwings"},
    {"CLX", "Cargolux"},
    {"CMI", "Continental Micron"},
    {"CMP", "Copa"},
    {"CNF", "Canaryfly"},
    {"CNO", "SAS Braathens"},
    {"CNV", "US Navy"},
    {"COA", "Continental"},
    {"COE", "Comtel Air"},
    {"COM", "Comair"},
    {"CPA", "Cathay Pacific"},
    {"CPN", "Caspian Airlines"},
    {"CPZ", "Compass Airlines"},
    {"CQH", "Spring Airlines"},
    {"CQN", "Chongqing"},
    {"CRK", "Hong Kong"},
    {"CRL", "Corsairfly"},
    {"CRO", "Crown Airways"},
    {"CSA", "Czech"},
    {"CSC", "Sichuan Airlines"},
    {"CSH", "Shanghai"},
    {"CSN", "China Southern"},
    {"CSX", "Choice Airways"},
    {"CSZ", "Shenzhen"},
    {"CTN", "Croatia"},
    {"CUA", "China United"},
    {"CUB", "Cubana de Aviacion"},
    {"CUD", "Air Cudlua"},
    {"CVA", "Air Chathams"},
    {"CWK", "Comores Airlines"},
    {"CWM", "Air Marshall Islan"},
    {"CXA", "Xiamen Airlines"},
    {"CYD", "Access Air"},
    {"CYH", "Yunnan Airlines"},
    {"CYP", "Cyprus Airways"},
    {"CZV", "Via Conectia"},
    {"DAF", "Danish AF"},
    {"DAH", "Air Algerie"},
    {"DAK", "First Flying"},
    {"DAL", "Delta"},
    {"DAO", "Daallo Airlines"},
    {"DAT", "Brussels"},
    {"DBK", "Dubrovnik Air"},
    {"DCD", "Air 26"},
    {"DEA", "Delta Aerotaxi"},
    {"DHI", "Adam Air"},
    {"DJB", "Djibouti"},
    {"DKH", "Juneyao Airlines"},
    {"DLA", "Air Dolomiti"},
    {"DLH", "Lufthansa"},
    {"DME", "Royal Flight"},
    {"DMO", "Domodedovo"},
    {"DNL", "Dutch Antilles Exp"},
    {"DNM", "Denim Air"},
    {"DNV", "Aeroflot-Don"},
    {"DOA", "Dominicana de Avia"},
    {"DOB", "Dobrolet"},
    {"DRD", "Air Madrid"},
    {"DRK", "Druk Air"},
    {"DRU", "Alrosa Mirny Air E"},
    {"DSM", "LAN Argentina"},
    {"DSV", "Direct Aero Servic"},
    {"DSY", "Dennis Sky"},
    {"DTA", "TAAG Angola"},
    {"DTR", "DAT"},
    {"DWA", "Dense Airways"},
    {"DWT", "Darwin Airline"},
    {"DYA", "Dynamic Airways"},
    {"EAA", "Eastok Avia"},
    {"EAL", "European Air Expre"},
    {"EAV", "Eastern Atlantic V"},
    {"ECA", "Eurocypria"},
    {"ECU", "Ecuavia"},
    {"EDV", "Endeavor"},
    {"EDW", "Edelweiss Air"},
    {"EEA", "Empresa Ecuatorian"},
    {"EEU", "Eurofly Service"},
    {"EFA", "Far Eastern Air Tr"},
    {"EFY", "EasyFly"},
    {"EGF", "American Eagle"},
    {"EGH", "BBN-Airways"},
    {"EGS", "Eagles Airlines"},
    {"EHN", "East Horizon"},
    {"EIA", "Evergreen Internat"},
    {"EIN", "Aer Lingus"},
    {"EJA", "NetJets"},
    {"EJU", "easyJet Europe"},
    {"ELA", "Eastland Air"},
    {"ELC", "Small Planet"},
    {"ELK", "ELK Airways"},
    {"ELL", "Estonian Air"},
    {"ELO", "Eurolot"},
    {"ELY", "El Al"},
    {"ENJ", "Enerjet"},
    {"ENT", "Enter Air"},
    {"ENY", "Envoy"},
    {"ENZ", "Jota Aviation"},
    {"ERO", "Sun D'Or"},
    {"ERR", "Era Alaska"},
    {"ERT", "Eritrean"},
    {"ESK", "SkyEurope"},
    {"ESR", "Eastar Jet"},
    {"ETD", "Etihad"},
    {"ETH", "Ethiopian"},
    {"EUD", "Air Italy Egypt"},
    {"EUV", "EuropeSky"},
    {"EVA", "EVA Air"},
    {"EVC", "Comfort Express Vi"},
    {"EWG", "Eurowings"},
    {"EXS", "Jet2"},
    {"EZA", "Eznis Airways"},
    {"EZE", "Eastern Airways"},
    {"EZY", "easyJet"},
    {"FAB", "First Air"},
    {"FAF", "French AF"},
    {"FBL", "Fly Brasil"},
    {"FCA", "First Choice"},
    {"FCB", "COBALT"},
    {"FCM", "Flybe Finland Oy"},
    {"FDB", "flydubai"},
    {"FDD", "Feeder Airlines"},
    {"FDX", "FedEx"},
    {"FEG", "FlyEgypt"},
    {"FFM", "Firefly"},
    {"FFT", "Frontier"},
    {"FFV", "Fly540"},
    {"FHE", "Hello"},
    {"FHI", "FlyHigh Airlines I"},
    {"FIF", "Air Finland"},
    {"FIN", "Finnair"},
    {"FIX", "Airfix Aviation"},
    {"FJI", "Fiji Airways"},
    {"FJM", "Fly Jamaica"},
    {"FKA", "Flying kangaroo"},
    {"FLB", "German Air Force -"},
    {"FLG", "Pinnacle"},
    {"FLI", "Atlantic Airways"},
    {"FLT", "Flight Alaska"},
    {"FLZ", "Air Florida"},
    {"FNA", "Norlandair"},
    {"FNY", "Finnish AF"},
    {"FOS", "Formosa Airlines"},
    {"FOX", "FOX Linhas Aereas"},
    {"FPT", "FlyPortugal"},
    {"FRE", "Freedom Air"},
    {"FRF", "Fly France"},
    {"FRL", "Freedom Airlines"},
    {"FTA", "Frontier Flying Se"},
    {"FVM", "Flugfelag Vestmann"},
    {"FWI", "Air Caraibes"},
    {"FWL", "Florida West Inter"},
    {"FXI", "Air Iceland"},
    {"FXX", "Felix Airways"},
    {"FYH", "Flyhy Cargo"},
    {"FYJ", "FLYJET"},
    {"FZA", "Fuzhou Airlines"},
    {"FZW", "Fly Africa Zimbabw"},
    {"GAF", "German AF"},
    {"GAI", "Moskovia"},
    {"GAO", "Golden Air"},
    {"GAP", "Air Philippines"},
    {"GBA", "Gulf Air Bahrain"},
    {"GBK", "Gabon Airlines"},
    {"GBL", "GB Airways"},
    {"GCA", "Grand Cru"},
    {"GCR", "Tianjin Airlines"},
    {"GDC", "Grand China Air"},
    {"GDR", "Gadair European"},
    {"GEC", "Lufthansa Cargo"},
    {"GER", "German Internation"},
    {"GFA", "Gulf Air"},
    {"GFG", "Georgian National"},
    {"GFT", "Gulfstream Interna"},
    {"GFY", "Greenfly"},
    {"GHB", "Ghana Internationa"},
    {"GIA", "Garuda"},
    {"GIE", "Elysian Airlines"},
    {"GIP", "Air Guinee Express"},
    {"GJS", "GoJet Airlines"},
    {"GLA", "Great Lakes"},
    {"GLG", "Aerolineas Galapag"},
    {"GLO", "Gol Transportes Ae"},
    {"GLP", "Globus"},
    {"GMI", "Germania"},
    {"GMR", "Golden Myanmar"},
    {"GNN", "Georgian Internati"},
    {"GOW", "Go Air"},
    {"GRL", "Air Greenland"},
    {"GSM", "Flyglobespan"},
    {"GTA", "City Airways"},
    {"GTI", "Atlas Air"},
    {"GUY", "Air Guyane"},
    {"GWI", "Germanwings"},
    {"GWY", "USA3000 Airlines"},
    {"GXG", "GermanXL"},
    {"GZP", "Gazpromavia"},
    {"HAF", "Hellenic AF"},
    {"HAG", "Hageland Aviation"},
    {"HAL", "Hawaiian"},
    {"HAM", "Haiti Ambassador"},
    {"HAY", "Hamburg Airways"},
    {"HBH", "Hebei Airlines"},
    {"HBR", "Hebradran Air Serv"},
    {"HCC", "Holidays Czech"},
    {"HCW", "Star1 Airlines"},
    {"HDA", "Cathay Dragon"},
    {"HEJ", "Hellas Jet"},
    {"HER", "Hex'Air"},
    {"HFR", "Heli France"},
    {"HHI", "Hamburg Internatio"},
    {"HKE", "Hong Kong Express"},
    {"HLF", "Hapagfly"},
    {"HLX", "TUIfly"},
    {"HMR", "North American Cha"},
    {"HNX", "Hankook Airline"},
    {"HOP", "Air France HOP"},
    {"HPY", "Happy Air"},
    {"HRM", "Hermes Airlines"},
    {"HSK", "Sky Europe"},
    {"HTH", "Helitt Lineas Aere"},
    {"HVK", "Turkish Air Force"},
    {"HVN", "Vietnam Airlines"},
    {"HWY", "Highland Airways"},
    {"HYM", "Himalayan"},
    {"HZA", "Horizon Airlines"},
    {"IAA", "Indonesian"},
    {"IAC", "Indian Airlines"},
    {"IAM", "Italian AF"},
    {"IAW", "Iraqi Airways"},
    {"IBB", "Binter Canarias"},
    {"IBE", "Iberia"},
    {"IBK", "Norwegian Air Inte"},
    {"IBS", "Iberia Express"},
    {"IBU", "Indigo"},
    {"IBX", "Ibex Airlines"},
    {"ICE", "Icelandair"},
    {"ICL", "CAL Cargo Air Line"},
    {"IDS", "Indonesia Sky"},
    {"IDX", "Indonesa Air Aisa"},
    {"IGO", "IndiGo"},
    {"IIA", "AIR INDOCHINE"},
    {"IIR", "INAVIA Internacion"},
    {"IKA", "Itek Air"},
    {"ILN", "Interair South Afr"},
    {"IMP", "Hellenic Imperial"},
    {"INE", "International Euro"},
    {"IPV", "Parmiss Airlines ("},
    {"IRA", "Iran Air"},
    {"IRC", "Iran Aseman"},
    {"IRK", "Kish Air"},
    {"IRM", "Mahan Air"},
    {"ISK", "Intersky"},
    {"ISR", "Israir"},
    {"ISS", "Meridiana"},
    {"ISV", "Islena De Inversio"},
    {"ISW", "Islas Airways"},
    {"ISX", "Island Spirit"},
    {"ITK", "Interlink"},
    {"ITX", "Imair Airlines"},
    {"ITY", "ITA Airways"},
    {"IWA", "Apache Air"},
    {"IWD", "Iberworld"},
    {"IXO", "OCEAN AIR CARGO"},
    {"IYE", "Yemenia"},
    {"JAA", "Japan Asia"},
    {"JAB", "Air Bagan"},
    {"JAF", "TUI fly Belgium"},
    {"JAI", "Jet Airways"},
    {"JAL", "Japan Airlines"},
    {"JAS", "Japan Air System"},
    {"JAZ", "JALways"},
    {"JBA", "Helijet"},
    {"JBU", "JetBlue"},
    {"JEF", "Jetflite"},
    {"JET", "Wind Jet"},
    {"JEX", "JAL Express"},
    {"JFU", "Jet4You"},
    {"JGN", "Jagson Airlines"},
    {"JIA", "PSA"},
    {"JJA", "Jeju Air"},
    {"JJP", "Jetstar Japan "},
    {"JKK", "Spanair"},
    {"JNA", "Jin Air"},
    {"JOR", "Blue Air"},
    {"JOY", "Joy Air"},
    {"JPU", "Jupiter Airlines"},
    {"JRB", "Jc royal.britannic"},
    {"JSA", "Jetstar Asia"},
    {"JSR", "Jusur airways"},
    {"JST", "Jetstar"},
    {"JTA", "Japan Transocean A"},
    {"JTO", "Jettor Airlines"},
    {"JZA", "Air Canada Jazz"},
    {"JZR", "Jazeera Airways"},
    {"KAC", "Kuwait"},
    {"KAL", "Korean Air"},
    {"KAP", "Cape Air"},
    {"KBR", "KoralBlue"},
    {"KBZ", "Air KBZ"},
    {"KCU", "Skyline Ulasim Tic"},
    {"KDA", "Kendell Airlines"},
    {"KEA", "Korea Express Air"},
    {"KEN", "Kenmore Air"},
    {"KFR", "Kingfisher"},
    {"KGL", "Kogalymavia Air Co"},
    {"KGO", "Korongo Airlines"},
    {"KHB", "Dalavia"},
    {"KHK", "Kharkiv Airlines"},
    {"KIL", "Kuban Airlines"},
    {"KIN", "Kinloss Flying Tra"},
    {"KIS", "Contact Air"},
    {"KJC", "Krasnojarsky"},
    {"KKK", "Atlasjet"},
    {"KLC", "KLM Cityhopper"},
    {"KLM", "KLM"},
    {"KLS", "Kal Star"},
    {"KMF", "Kam Air"},
    {"KMM", "KM Malta"},
    {"KND", "Kan Air"},
    {"KNE", "Nas Air"},
    {"KNI", "KD Avia"},
    {"KOL", "SOCHI AIR"},
    {"KOQ", "Kostromskie aviali"},
    {"KOR", "Air Koryo"},
    {"KQA", "Kenya Airways"},
    {"KRP", "Carpatair"},
    {"KRY", "Russkie Krylya"},
    {"KSM", "Kosmos"},
    {"KSY", "KSY"},
    {"KSZ", "Sunrise Airways"},
    {"KUH", "Kush Air"},
    {"KYA", "Alghanim"},
    {"KZK", "Air Kazakhstan"},
    {"KZR", "Air Astana"},
    {"KZU", "Kuzu Airlines Carg"},
    {"LAA", "Libyan Arab"},
    {"LAJ", "British Mediterran"},
    {"LAM", "Linhas A"},
    {"LAN", "LATAM"},
    {"LAO", "Lao Airlines"},
    {"LAP", "TAM Mercosur"},
    {"LAV", "AlbaStar"},
    {"LBC", "Albanian"},
    {"LBL", "Line Blue"},
    {"LBT", "Nouvel Air Tunisie"},
    {"LDA", "Lauda Air"},
    {"LFA", "Air Alfa"},
    {"LGL", "Luxair"},
    {"LGW", "Luftfahrtgesellsch"},
    {"LHN", "Express One Intern"},
    {"LIA", "Leeward Islands Ai"},
    {"LIL", "FlyLal"},
    {"LIX", "LionXpress"},
    {"LJJ", "Luchsh Airlines "},
    {"LLC", "FlyLAL Charters"},
    {"LLM", "Yamal Airlines"},
    {"LMM", "LCM AIRLINES"},
    {"LMU", "AlMasria Universal"},
    {"LNE", "Aerolane"},
    {"LNI", "Lion Mentari"},
    {"LOC", "Locair"},
    {"LOF", "Trans States"},
    {"LOG", "Loganair"},
    {"LOO", "LSM Airlines"},
    {"LOT", "LOT Polish"},
    {"LPE", "LAN Peru"},
    {"LPR", "L"},
    {"LRC", "LACSA"},
    {"LTC", "LatCharter"},
    {"LTD", "Southern Airways E"},
    {"LTE", "LTE International"},
    {"LTO", "LTU Austria"},
    {"LTR", "Lufttransport"},
    {"LTU", "Air Lituanica"},
    {"LTY", "Liberty Airways"},
    {"LUR", "Atlantis European"},
    {"LXP", "LAN Express"},
    {"LXR", "Air Luxor"},
    {"LZB", "Bulgaria Air"},
    {"MAA", "MasAir"},
    {"MAC", "Malta Air Charter"},
    {"MAH", "Malev"},
    {"MAI", "Mauritania Airline"},
    {"MAK", "MAT Macedonian"},
    {"MAL", "Morningstar Air Ex"},
    {"MAS", "Malaysia"},
    {"MAU", "Air Mauritius"},
    {"MAV", "Maldivo Airlines"},
    {"MAY", "Malta Air"},
    {"MCA", "MCA Airlines"},
    {"MCK", "Macair Airlines"},
    {"MDA", "Mandarin"},
    {"MDG", "Air Madagascar"},
    {"MDL", "Mandala Airlines"},
    {"MDO", "Domenican"},
    {"MDP", "Medallion Air"},
    {"MDV", "Moldavian"},
    {"MDW", "Midway Airlines"},
    {"MEA", "MEA"},
    {"MEP", "Midwest Airlines"},
    {"MES", "Mesaba Airlines"},
    {"MGL", "MIAT Mongolian"},
    {"MGX", "Montenegro"},
    {"MIC", "Mint Airways"},
    {"MJG", "Michael Airlines"},
    {"MJP", "Air Majoro"},
    {"MJX", "Euroline"},
    {"MKD", "MAT Airways"},
    {"MKG", "Air Mekong"},
    {"MKU", "Island Air (WP)"},
    {"MLA", "40-Mile Air"},
    {"MLD", "Air Moldova"},
    {"MMM", "Myanmar Airways In"},
    {"MNA", "Merpati Nusantara"},
    {"MNB", "MNG Airlines"},
    {"MNO", "Mango"},
    {"MNP", "Spirit of Manila"},
    {"MON", "Monarch Airlines"},
    {"MOV", "VIM Airlines"},
    {"MPD", "Air Plus Comet"},
    {"MPE", "Canadian North"},
    {"MPH", "Martinair"},
    {"MRS", "Marusya Airways"},
    {"MSE", "EgyptAir Express"},
    {"MSI", "Motor Sich"},
    {"MSR", "EgyptAir"},
    {"MTW", "Mauritania"},
    {"MVD", "Kavminvodyavia"},
    {"MWA", "Midwest Airlines ("},
    {"MWI", "Malaysia Wings"},
    {"MXA", "Mexicana de Aviaci"},
    {"MXD", "Malindo Air"},
    {"MXI", "MexicanaLink"},
    {"MXL", "Maxair"},
    {"MXY", "Breeze"},
    {"MYA", "Myflug"},
    {"MYD", "Maya Island Air"},
    {"MYP", "Mann Yadanarpon"},
    {"MYT", "MyTravel Airways"},
    {"NAF", "Netherlands AF"},
    {"NAK", "Arik Niger"},
    {"NAS", "Nasair"},
    {"NAX", "Norwegian"},
    {"NCF", "Norfolk County Fli"},
    {"NCR", "National Air Cargo"},
    {"NDC", "FlyNordic"},
    {"NDN", "Transportes Aereos"},
    {"NEA", "New England"},
    {"NGB", "Nordic Global"},
    {"NIA", "Nile Air"},
    {"NIG", "Aero Contractors"},
    {"NJS", "National Jet Syste"},
    {"NKF", "Barents AirLink"},
    {"NKS", "Spirit"},
    {"NLH", "Norwegian Long Hau"},
    {"NLY", "Niki"},
    {"NMA", "Nesma Airlines"},
    {"NMB", "Air Namibia"},
    {"NMI", "Pacific Wings"},
    {"NOK", "Nok Air"},
    {"NOS", "Neos"},
    {"NOW", "Norwegian AF"},
    {"NOZ", "Norwegian"},
    {"NRS", "Norra"},
    {"NSE", "SATENA"},
    {"NSZ", "Norwegian"},
    {"NTJ", "NextJet"},
    {"NTM", "North American"},
    {"NTW", "Nationwide"},
    {"NVR", "Novair"},
    {"NWA", "Northwest"},
    {"NWG", "Norwegian"},
    {"NXB", "NEXT Brasil"},
    {"NYT", "Yeti Airlines "},
    {"OAB", "Orbit Airlines Aze"},
    {"OAE", "Omni Air Internati"},
    {"OAI", "Orbit Internationa"},
    {"OAL", "Olympic"},
    {"OAN", "Orbit Atlantic"},
    {"OAR", "Orbit Regional"},
    {"OAW", "Helvetic Airways"},
    {"OBS", "Orbest"},
    {"OBT", "Orbit Airlines"},
    {"OCA", "Aserca Airlines"},
    {"OEA", "Orient Thai"},
    {"OGN", "Origin Pacific"},
    {"OHK", "Oasis Hong Kong"},
    {"OHY", "Onur Air"},
    {"OLA", "Overland Airways"},
    {"OLS", "Sol Lineas Aereas"},
    {"OLT", "Ostfriesische Luft"},
    {"OMA", "Oman Air"},
    {"OME", "Homer Air"},
    {"ONE", "Oceanair"},
    {"OOM", "Zoom Airlines"},
    {"ORB", "Orenburg"},
    {"ORC", "Orchid Airlines"},
    {"ORG", "Orenburzhie"},
    {"OTG", "One Two Go"},
    {"OTJ", "Fly Romania"},
    {"OZJ", "Ozjet Airlines"},
    {"OZW", "Skywest Airlines"},
    {"PAL", "Philippine"},
    {"PAO", "Polynesian"},
    {"PBA", "PB Air"},
    {"PBD", "Pobeda"},
    {"PCO", "Pacific Coastal"},
    {"PDC", "Potomac Air"},
    {"PDT", "Piedmont"},
    {"PEC", "Pacific East Asia"},
    {"PEL", "Aeropelican Air Se"},
    {"PEN", "Peninsula"},
    {"PFL", "Pacific Flier"},
    {"PGA", "Portugalia"},
    {"PGT", "Pegasus"},
    {"PIA", "Pakistan Internati"},
    {"PIC", "Jetstar Pacific"},
    {"PKV", ""},
    {"PLI", "Aeroper"},
    {"PLR", "Northwestern Air"},
    {"PMT", "PMTair"},
    {"PMW", "Paramount"},
    {"PNR", "PAN Air"},
    {"POE", "Porter"},
    {"POT", "Polet"},
    {"PPL", "Air Pegasus"},
    {"PPW", "Royal Phnom Penh"},
    {"PQW", "PanAm World"},
    {"PRF", "Precision Air"},
    {"PSA", "Pacific Island"},
    {"PSB", "Syrian Pearl"},
    {"PTB", "Passaredo Transpor"},
    {"PTI", "Privatair"},
    {"PUA", "PLUNA"},
    {"PYA", "Pouya Air"},
    {"PYB", "All America BOPY"},
    {"PZY", "Zapolyarie"},
    {"QAX", "QatXpress"},
    {"QER", "SOCHI AIR CHATER"},
    {"QFA", "Qantas"},
    {"QFZ", "Fars Air Qeshm"},
    {"QQQ", "ENTERair"},
    {"QTR", "Qatar Airways"},
    {"QXE", "Horizon Air"},
    {"RAB", "Rainbow Air (RAI)"},
    {"RAC", "Royal Air Cambodge"},
    {"RAE", "Regional"},
    {"RAM", "Royal Air Maroc"},
    {"RAR", "Air Rarotonga"},
    {"RAW", "Royal Airways"},
    {"RAY", "Rainbow Air Canada"},
    {"RBA", "Royal Brunei"},
    {"RBG", "Air Arabia Egypt"},
    {"RBY", "Vision Airlines (V"},
    {"RCH", "US Air Mobility"},
    {"REA", "Aer Arann"},
    {"REP", "Regional Paraguaya"},
    {"REU", "Air Austral"},
    {"RFJ", "Royal Falcon"},
    {"RFR", "Royal Air Force"},
    {"RGG", "TransRussiaAirline"},
    {"RIT", "Asian Spirit"},
    {"RJA", "Royal Jordanian"},
    {"RJD", "Rotana Jet"},
    {"RKA", "Air Afrique"},
    {"RLA", "Airlinair"},
    {"RLN", "Aero Lanka"},
    {"RLU", "Rusline"},
    {"RLX", "Go2Sky"},
    {"RMK", "Simrik Airlines"},
    {"RNA", "Royal Nepal"},
    {"RNE", "Air Salone"},
    {"RNV", "Armavia"},
    {"RNX", "1Time Airline"},
    {"RNY", "Rainbow Air US"},
    {"RON", "Nauru Air Corporat"},
    {"ROT", "Tarom"},
    {"ROU", "Air Canada Rouge"},
    {"RPA", "Republic"},
    {"RPB", "AeroRep"},
    {"RPH", "Republic Express"},
    {"RPO", "Rainbow Air Polyne"},
    {"RRJ", "AirRussia"},
    {"RSD", "Russia State Trans"},
    {"RSH", "Air Sahara"},
    {"RSI", "Air Sunshine"},
    {"RSJ", "RusJet"},
    {"RSP", "Jet Suite"},
    {"RSR", "Aero-Service"},
    {"RSU", "Aerosur"},
    {"RSY", "I-Fly"},
    {"RTE", "Aeronorte"},
    {"RUE", "Rainbow Air Euro"},
    {"RUK", "Ryanair UK"},
    {"RUS", "Cirrus Airlines"},
    {"RWD", "Rwandair Express"},
    {"RWW", "Fly Europa"},
    {"RWZ", "Red Wings"},
    {"RXA", "Regional Express"},
    {"RXR", "REXAIR VIRTUEL"},
    {"RYA", "Ryan Air Services"},
    {"RYN", "Ryan International"},
    {"RYR", "Ryanair"},
    {"RZO", "SATA International"},
    {"SAA", "South African"},
    {"SAE", "SOCHI AIR EXPRESS"},
    {"SAI", "Shaheen Air Intern"},
    {"SAL", "Spike Airlines"},
    {"SAS", "SAS"},
    {"SAT", "SATA Air Acores"},
    {"SAY", "ScotAirways"},
    {"SBD", "Snowbird"},
    {"SBI", "S7 Airlines"},
    {"SBS", "Seaborne"},
    {"SCE", "Scenic Airlines"},
    {"SCO", "Scoot"},
    {"SCQ", "Scoot"},
    {"SCW", "Malmo Aviation"},
    {"SCX", "Sun Country"},
    {"SDI", "San Dima Air"},
    {"SDM", "Rossiya-Russian"},
    {"SDR", "City Airline"},
    {"SEA", "Southeast Air"},
    {"SEH", "Sky Express"},
    {"SEJ", "Spicejet"},
    {"SEN", "Sevenair"},
    {"SEU", "XL Airways France"},
    {"SEY", "Air Seychelles"},
    {"SFJ", "Star Flyer"},
    {"SGG", "Senegal Airlines"},
    {"SGY", "Skagway Air Servic"},
    {"SHA", "Sharp Airlines"},
    {"SHD", "Sahara Airlines"},
    {"SHT", "BA Shuttle"},
    {"SIA", "Singapore"},
    {"SIB", "Sibaviatrans"},
    {"SIH", "Skynet Airlines"},
    {"SJM", "Svyaz Rossiya"},
    {"SJO", "Spring Airlines Ja"},
    {"SJS", "Southjet"},
    {"SJU", "Skyjet Airlines"},
    {"SJY", "Sriwijaya Air"},
    {"SKU", "Sky Airline"},
    {"SKV", "Sky Regional"},
    {"SKW", "SkyWest"},
    {"SKX", "Skyways Express"},
    {"SKY", "Skymark Airlines"},
    {"SLC", "Salsa d\\'Haiti"},
    {"SLI", "Aerolitoral"},
    {"SLK", "SilkAir"},
    {"SLM", "Surinam Airways"},
    {"SMJ", "Avient Aviation"},
    {"SMW", "Carpatair Flight T"},
    {"SMX", "Alitalia Express"},
    {"SMY", "Sama Airlines"},
    {"SNB", "Sterling"},
    {"SNC", "Air Cargo Carriers"},
    {"SNJ", "Skynet Asia"},
    {"SOA", "Southern Air Chart"},
    {"SOL", "Solomon Airlines"},
    {"SOU", "Southern Airways"},
    {"SOV", "Saratov Aviation D"},
    {"SOZ", "Sat Airlines"},
    {"SPI", "South Pacific Isla"},
    {"SPM", "Air Saint Pierre"},
    {"SQC", "Singapore Airlines"},
    {"SQH", "SeaPort Airlines"},
    {"SRB", "Solar Air"},
    {"SRH", "Siem Reap"},
    {"SRN", "Sprintair"},
    {"SRQ", "South East Asian"},
    {"SRY", "ViaAir"},
    {"SSA", "All America US"},
    {"SSV", "Skyservice"},
    {"STP", "STP Airways"},
    {"STU", "Servicios de Trans"},
    {"SUD", "Sudan Airways"},
    {"SUI", "Swiss AF"},
    {"SUW", "Interavia"},
    {"SVA", "Saudia"},
    {"SVG", "SVG Air"},
    {"SVR", "Ural Airlines"},
    {"SVS", "SAS Link"},
    {"SVW", "Air Leap"},
    {"SWA", "Southwest"},
    {"SWD", "Southern Winds"},
    {"SWM", "Sky Angkor Airline"},
    {"SWR", "Swiss"},
    {"SWU", "Swiss European Air"},
    {"SWV", "Swe Fly"},
    {"SXR", "Sky Express"},
    {"SXS", "SunExpress"},
    {"SYL", "Aircompany Yakutia"},
    {"SYR", "Syrian Arab"},
    {"SYX", "Skywalk Airlines"},
    {"SZB", "Aerolineas heredas"},
    {"SZS", "SAS Connect"},
    {"SZZ", "SUR Lineas Aereas"},
    {"TAE", "TAME"},
    {"TAH", "Air Moorea"},
    {"TAK", "Tatarstan"},
    {"TAM", "LATAM"},
    {"TAN", "Zanair"},
    {"TAO", "Aeromar"},
    {"TAP", "TAP Portugal"},
    {"TAR", "Tunisair"},
    {"TAT", "Grupo TACA"},
    {"TBZ", "TrasBrasil"},
    {"TCF", "Shuttle America"},
    {"TCG", "Thai Air Cargo"},
    {"TCV", "TACV"},
    {"TCW", "Thomas Cook"},
    {"TCX", "Thomas Cook"},
    {"TDK", "Transavia Denmark"},
    {"TEZ", "Tez Jet Airlines"},
    {"TFL", "TUI fly NL"},
    {"TFN", "Norwegian Aviation"},
    {"TGN", "Trigana Air Servic"},
    {"TGW", "Tiger Airways Aust"},
    {"TGZ", "Georgian Airways"},
    {"THA", "Thai"},
    {"THI", "TransHolding"},
    {"THK", "Turk Hava Kurumu H"},
    {"THS", "TransBrasil"},
    {"THT", "Air Tahiti Nui"},
    {"THY", "Turkish"},
    {"TIB", "TRIP Linhas A"},
    {"TIL", "Tajikistan Interna"},
    {"TJA", "T.J. Air"},
    {"TJT", "Twin Jet"},
    {"TKS", "Tomsk-Avia"},
    {"TLA", "Translift"},
    {"TMA", "Trans Mediterranea"},
    {"TNA", "TransAsia"},
    {"TNM", "Tiara Air"},
    {"TNS", "Transilvania"},
    {"TNU", "TransNusa Air"},
    {"TOK", "Airlines PNG"},
    {"TOM", "TUI Airways"},
    {"TOS", "Tropic Air"},
    {"TPA", "TAMPA"},
    {"TRA", "Transavia"},
    {"TRK", "Turkuaz Airlines"},
    {"TRS", "AirTran Airways"},
    {"TSC", "Air Transat"},
    {"TSO", "Transaero"},
    {"TTZ", "Transair"},
    {"TUA", "Turkmenistan"},
    {"TUI", "TUI fly"},
    {"TUR", "ATUR"},
    {"TUS", "ABSA - Aerolinhas"},
    {"TVF", "Transavia France"},
    {"TVJ", "Thai Vietjet Air"},
    {"TVS", "Smartwings"},
    {"TWB", "Tway Airlines"},
    {"TWD", "Turkish Wings Dome"},
    {"TWN", "Avialeasing Aviati"},
    {"TXW", "Texas Wings"},
    {"TYR", "Tyrolean Airways"},
    {"TYS", "TransHolding Syste"},
    {"UAC", "United Air Charter"},
    {"UAE", "Emirates"},
    {"UAL", "United"},
    {"UAT", "Ukraine Atlantic"},
    {"UAY", "University of Birm"},
    {"UBA", "Myanma Airways"},
    {"UBD", "United Airways"},
    {"UBG", "US-Bangla"},
    {"UCA", "CommutAir"},
    {"UDC", "DonbassAero"},
    {"UDN", "Dniproavia"},
    {"UGX", "East African"},
    {"UIA", "Uni Air"},
    {"UJX", "AtlasGlobal Ukrain"},
    {"UKM", "UM Airlines"},
    {"UMK", "Yuzhmashavia"},
    {"UPA", "Air Foyle"},
    {"UPS", "UPS"},
    {"URN", "Turan Air"},
    {"USA", "US Airways"},
    {"USH", "US Helicopter"},
    {"UTA", "UTair Aviation"},
    {"UTY", "Alliance"},
    {"UWW", "LSM International"},
    {"UZB", "Uzbekistan"},
    {"VAS", "ATRAN Cargo"},
    {"VAX", "V Air"},
    {"VBW", "Air Burkina"},
    {"VCV", "Conviasa"},
    {"VDA", "Volga-Dnepr"},
    {"VEX", "Virgin Express"},
    {"VFC", "Vasco Air"},
    {"VGN", "Virgin Nigeria"},
    {"VIA", "VIA Lineas Aereas"},
    {"VIM", "Air VIA"},
    {"VIR", "Virgin Atlantic"},
    {"VIS", "Vision Air Interna"},
    {"VIV", "Viva Aerobus"},
    {"VJC", "VietJet"},
    {"VKG", "Sunclass"},
    {"VKH", "Viking Hellas"},
    {"VKJ", "VickJet"},
    {"VLE", "Volare Airlines"},
    {"VLG", "Vueling"},
    {"VLK", "Vladivostok Air"},
    {"VLM", "VLM Airlines"},
    {"VLO", "Varig Log"},
    {"VLU", "Valuair"},
    {"VNP", "Virgin Pacific"},
    {"VOE", "Volotea"},
    {"VOI", "Volaris"},
    {"VOO", "Volotea"},
    {"VOZ", "Virgin Australia"},
    {"VQI", "Flyme (VP)"},
    {"VRD", "Virgin America"},
    {"VRN", "VRG Linhas Aereas"},
    {"VSP", "VASP"},
    {"VSV", "Scat Air"},
    {"VTA", "Air Tahiti"},
    {"VTI", "Air Vistara"},
    {"VUE", "AD Aviation"},
    {"VUN", "Air Ivoire"},
    {"VVC", "VivaColombia"},
    {"VVM", "Viva Macau"},
    {"VVN", "88"},
    {"VWA", "Virginwings"},
    {"WAJ", "AirAsia Japan"},
    {"WAL", "Western Airlines"},
    {"WAU", "Wizz Air Ukraine"},
    {"WBA", "Finncomm"},
    {"WEB", "WebJet Linhas A"},
    {"WEN", "WestJet Encore"},
    {"WER", "AeroWorld "},
    {"WFX", "Westfalia Express"},
    {"WIF", "Wideroe"},
    {"WJA", "WestJet"},
    {"WLC", "Welcome Air"},
    {"WOA", "World Airways"},
    {"WON", "Wings Air"},
    {"WOW", "Air Southwest"},
    {"WRC", "Wind Rose"},
    {"WSS", "World Scale"},
    {"WTA", "Africa West"},
    {"WTJ", "Whitejets"},
    {"WVL", "Wizz Air Hungary"},
    {"WZZ", "Wizz Air"},
    {"XAN", "Southjet cargo"},
    {"XAU", "XAIR USA"},
    {"XAX", "AirAsia X"},
    {"XBM", "CBM America"},
    {"XEL", "Excel Charter"},
    {"XLA", "Excel Airways"},
    {"XLF", "XL Airways"},
    {"XOJ", "XOJET"},
    {"XPT", "XPTO"},
    {"XSR", "Executive AirShare"},
    {"YCC", "Ciel Canadien"},
    {"YCP", "Canadian National"},
    {"YEL", "Yellowtail"},
    {"YEP", "YES Airways"},
    {"YZZ", "LSM AIRLINES "},
    {"ZCS", "Southjet connect"},
    {"ZNA", "Zenith Internation"},
    {"ZTF", "Mongolian Internat"},
    {"ZTT", "ZABAIKAL AIRLINES"},
    {"ZXY", "Japan Regio"},
    {"ZZZ", "Zabaykalskii"},
};
#define AIRLINE_COUNT (sizeof(AIRLINES)/sizeof(AIRLINES[0]))
